//! `coco_rt` — Coco native runtime (compiled from C).
//!
//! The actual runtime is implemented in C under `c/` and compiled to a static
//! library by `build.rs` (using the `cc` crate). This Rust crate is a thin
//! marker: it exists so that `coco_cli` (and others) can depend on `coco_rt`,
//! which forces Cargo to run this crate's build script — compiling the C and
//! emitting `cargo:rustc-link-lib=static=coco_rt` so the archive is linked into
//! the final binary.
//!
//! The codegen (`coco_codegen`) declares the runtime functions (`coco_make_int`,
//! `coco_add`, `coco_list_new`, etc.) as external C-ABI symbols and emits calls
//! to them; this crate provides those symbols at link time. See `c/coco_rt.h`
//! for the value model and the adaptive numeric tower.
//!
//! Why C and not Rust `extern "C"`? Precise layout control over the tagged
//! value struct, a natural fit for LLVM-emitted code, and the static archive is
//! reliably produced via `cc::Build::compile` (the previous `staticlib`
//! crate-type was not emitted transitively when coco_rt was only an rlib dep).
#![allow(clippy::missing_docs_in_private_items)]

/// Marker so the crate has a public item; dependents reference it to ensure the
/// crate (and thus its build script) is part of the build graph.
pub struct CocoRuntime;

impl CocoRuntime {
    /// The runtime version, for diagnostics.
    pub const VERSION: &str = "0.1.0";
}

/// Generated by `build.rs`: the absolute path to `libcoco_rt.a`. The CLI uses
/// this to link a user-compiled native binary (whose `cc` invocation is a
/// separate process outside Cargo's link step).
pub mod path {
    include!(concat!(env!("OUT_DIR"), "/coco_rt_path.rs"));
}
