[package]
name = "coco_interpreter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
tree-walker = []

[dependencies]
coco_syntax = { path = "../coco_syntax" }
coco_span = { path = "../coco_span" }
coco_parser = { path = "../coco_parser" }
coco_gc = { path = "../coco_gc" }
num-bigint = { workspace = true }
num-traits = { workspace = true }
regex = { workspace = true }
sha2 = { workspace = true }
rusqlite = { workspace = true }
mio = { workspace = true }
