//! Build script for coco_rt: compiles the C runtime sources into a static
//! library and emits `cargo:rustc-link-lib` so any crate depending on coco_rt
//! (with the `native` feature) links it automatically.
//!
//! This replaces the previous `crate-type = ["staticlib","rlib"]` Rust approach,
//! which suffered from Cargo not building the staticlib target transitively
//! (only the rlib was built when coco_rt was a dep of coco_cli). Compiling C
//! via the `cc` crate and emitting `rustc-link-lib=static=coco_rt` guarantees
//! the archive is produced and linked whenever coco_rt is in the build graph.

use std::path::PathBuf;

fn main() {
    let cdir = PathBuf::from("c");
    let files = ["c/value.c", "c/bignum.c", "c/arith.c", "c/collections.c"];

    // Sanity: warn if a source file is missing rather than failing obscurely.
    for f in &files {
        if !PathBuf::from(f).exists() {
            println!("cargo:warning=coco_rt: missing source file {}", f);
        }
    }

    let mut build = cc::Build::new();
    build
        .files(&files)
        .include(&cdir)
        // The runtime is C11; enable warnings during dev but don't hard-fail.
        .warnings(true)
        .flag_if_supported("-std=c11")
        .flag_if_supported("-Wno-unused-function");

    // Compile to a static archive named libcoco_rt.a.
    build.compile("coco_rt");

    // Emit link directives so dependents link the static lib by name. The
    // `cc` crate already adds the search path for its output dir; the
    // `rustc-link-lib` makes the archive a required link input.
    println!("cargo:rustc-link-lib=static=coco_rt");

    // Expose the absolute archive path to the CLI so it can pass it to the
    // runtime `cc` link of a user-compiled native binary (that link is a
    // separate process, outside Cargo's link step, so it can't rely on
    // rustc-link-lib alone). cc::Build::compile produces libcoco_rt.a in
    // OUT_DIR; we write its path to a generated source file that coco_rt's
    // lib.rs includes as a `const`, so any dependent (coco_cli) can read it
    // at runtime. (cargo:rustc-env from a dependency does NOT reach
    // dependents' compilation, so env! in coco_cli wouldn't see it.)
    let out_dir = std::env::var_os("OUT_DIR").expect("OUT_DIR set for build scripts");
    let archive = PathBuf::from(&out_dir).join("libcoco_rt.a");
    let generated = PathBuf::from(&out_dir).join("coco_rt_path.rs");
    std::fs::write(
        &generated,
        format!(
            "// Generated by coco_rt/build.rs. The absolute path to libcoco_rt.a.\n\
             pub const ARCHIVE_PATH: &str = {:?};\n",
            archive.to_string_lossy()
        ),
    )
    .expect("write coco_rt_path.rs");
    // Re-export the path via env as well (harmless; some tooling reads it).
    println!("cargo:rustc-env=COCO_RT_LIB={}", archive.display());

    // Re-run if any C source or header changes.
    println!("cargo:rerun-if-changed=c/coco_rt.h");
    for f in &files {
        println!("cargo:rerun-if-changed={}", f);
    }
    println!("cargo:rerun-if-changed=build.rs");
}
